name: '"AWS CodeBuild run build" Action For GitHub Actions'
description: 'Execute CodeBuild::startBuild for the current repo.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  project-name:
    description: 'AWS CodeBuild Project Name'
    required: true
  buildspec-override:
    description: 'Buildspec Override'
    required: false
  cache-override-type:
    description: 'Cache Override. Either NO_CACHE or S3 or LOCAL.'
    required: false
  cache-override-location:
    description: 'Cache Override. Location to cache.'
    required: false
  cache-override-modes:
    description: 'Cache Override. Comma separated list of cache modes.'
    required: false
  compute-type-override:
    description: 'ComputeType Override'
    required: false
  privileged-mode-override:
    description: 'PriviledgedMode Override'
    required: false
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
