name: '"AWS CodeBuild run build" Action For GitHub Actions'
description: 'Execute CodeBuild::startBuild for the current repo.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  project-name:
    description: 'AWS CodeBuild Project Name'
    required: true
  buildspec-override:
    description: 'Buildspec Override'
    required: false
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
  detach-build:
    description: 'True if you do not need to wait the build execution. Otherwise this action will wait the completion'
    required: false
  additional-parameters:
    description: 'Stringified JSON object that are additional request parameters sent to CodeBuild.'
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
